name: ai_campus_helpdesk
description: "A Smart Campus AI Assistant for IIT Bhilai."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # AI and Networking
  http: ^1.2.2
  image_picker: ^1.1.2
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  
  # Utilities
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png