name: ai_campus_helpdesk
description: "A Smart Campus AI Assistant for IIT Bhilai."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # AI and Networking
  image_picker: ^1.1.2
  http: ^1.2.2
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  
  # Utilities
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Ensure you have a folder named 'assets' with a file named 'logo.png' inside
  assets:
    - assets/logo.png